# Generated by Django 3.1 on 2020-09-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('projects', '0003_auto_20200829_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_topic', to='topics.topic'),
        ),
    ]
