# Generated by Django 3.1 on 2020-10-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
