# Generated by Django 3.1 on 2021-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_action_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
