# Generated by Django 3.1 on 2020-09-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('projects', '0003_auto_20200829_0907'),
        ('tasks', '0002_auto_20200904_1527'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_action_relation', to='actions.action'),
        ),
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_project_relation', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_task_relation', to='tasks.task'),
        ),
    ]
