# Generated by Django 3.1 on 2021-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='excludeFromReports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='taskProgress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
